#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace ClemyAcademyApp {
    namespace Controls {
        ref class PageHeader;
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class StackPanel;
                ref class TextBlock;
            }
        }
    }
}

namespace ClemyAcademyApp
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class UserProfile : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::ClemyAcademyApp::Controls::PageHeader^ pageHeader;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ fir;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ sec;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ thir;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ fourt;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ fifth;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ six;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ count;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ countblock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Lang;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Langblock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Passblock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ passtextblock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ emailblock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ emailtextblock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ nameblock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ fullnameblock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ usernameblock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ userblock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ title;
    };
}

